export const GET_POPULAR_SUCCESS='GET_POPULAR_SUCCESS'
export const GET_POPULAR_LOADING='GET_POPULAR_LOADING'
export const GET_POPULAR_ERROR='GET_POPULAR_ERROR'


export const GET_REPOSITORIES_SUCCESS='GET_REPOSITORIES_SUCCESS'
export const GET_REPOSITORIES_LOADING='GET_REPOSITORIES_LOADING'
export const GET_REPOSITORIES_ERROR='GET_REPOSITORIES_ERROR'
